name: release

on:
  push:
    branches:
      - master

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          name: v1.0.${{ github.run_number }}
          tag_name: v1.0.${{ github.run_number }}
          draft: false
          prerelease: false
          generate_release_notes: false
    outputs:
      tag: v.1.0.${{ github.run_number }}

  build_releases:
    name: Build Releases
    needs: create_release
    strategy:
      matrix:
        platform: [ubuntu, macos]
        include:
          - os: ubuntu-latest
            suffix: ubuntu

    runs-on: ${{ format('{0}-latest', matrix.platform) }}
    permissions: write-all

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'

      - name: Build binary
        run: |
           echo ${{ secrets.CLIENT_ID }}
           go build -o 'cmdg-${{ matrix.platform }}' -ldflags '-X main.InitId=${{ secrets.CLIENT_ID }} -X main.InitSecret=${{ secrets.CLIENT_SECRET }}' ./cmd/cmdg

      - name: Release binary
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.create_release.outputs.tag }}
          files: cmdg-${{ matrix.platform }}


